version: "2.4"
services:
  postgres:
    container_name: postgres
    image: raywu60kg/postgres:0.1.0
    restart: always
    ports:
      - 5432:5432
    network_mode: "host"

  metabase:
    container_name: metabase
    image: metabase/metabase:v0.37.9
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=raywu
      - MB_DB_PASS=raywu60kg
      - MB_DB_HOST=localhost
    ports:
      - 3000:3000
    network_mode: "host"
    depends_on:
      - postgres
